name: Monthly Go Run

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  run_go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Update
        id: update
        run: |
          go run -v ./cmd/cazilla -out mozilla_included.pem
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Update CA list" || exit 0
          CURRENT_TAG=$(git tag --sort=version:refname | tail -n 1)
          NEW_TAG=v$(go run github.com/xchacha20-poly1305/gvgo/cmd/bumpversion@v0.6.0-beta.1 $CURRENT_TAG 0 0 1)
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          git switch -c master || true # If not in other branch
          git tag $NEW_TAG
          git push origin master $NEW_TAG

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: steps.update.outputs.new_tag != ''
        with:
          tag_name: ${{ steps.update.outputs.new_tag }}
          files: ./mozilla_included.pem