name: Monthly Go Run

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  run_go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Update
        run: |
          go run -v ./cmd/cazilla -out mozilla_included.pem
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Update CA list"
